### PR TITLE
feat: add metadata export and import dags for 2.6.3

### PR DESCRIPTION
**Pull request by pshen**
*Issue #53*

*Description of changes:* 
AWS has released MWAA version 2.6.3. After checking https://github.com/apache/airflow/tree/main/airflow/migrations/versions, there was no change to the exported database tables between 2.5.1 and 2.6.3, so we could reuse the dag scripts from version 2.5.1.

Also compared
https://airflow.apache.org/docs/apache-airflow/2.5.1/database-erd-ref.html
https://airflow.apache.org/docs/apache-airflow/2.6.3/database-erd-ref.html

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by onisim-iacob** [comment]
Hi,

Did you manage to test this? I deployed MWAA 2.6.3 with the same DAGS and it throws an error. Even though the ERD didn't change, keep in mind that some dependencies have changed. In this case the CSVs are created on S3 but when DAG finishes, tries to send the  token confirmation back to the Step Function and it fails. Quite frustrating, because I thought the same as you... This AWS repo seems kind of forgotten by AWS...

image

The error talks about Lambda. I managed to extract the requirements from MWAA and maybe the issue is the difference on this library? Idk...

- MWAA 2.5.1: 
  - apache-airflow-providers-amazon==7.1.0

- MWAA 2.6.3:
  - apache-airflow-providers-amazon==8.2.0

**Comment by pshen** [comment]
Hi @onisim-iacob, actually no need to explicitly pin the version of apache-airflow-providers-amazon. MWAA has provided constraints file automatically, see here: https://docs.aws.amazon.com/mwaa/latest/userguide/airflow-versions.html.

I tested both DAGs, actually never had problem with export, but did have a small problem with import. Especially when re-importing the connections, the type for port has a problem. I've fixed it, but not pushed yet.

**Comment by onisim-iacob** [comment]
He thanks a lot! @pshen !!

I'm currently working on the MWAA 2.6.1 the errors are very strange. I'll test the changes from your repo regarding the import. Thanks a lot!!! 

I hope your PR gets approved soon, take care!

**Comment by pshen** [comment]
Hi @onisim-iacob 
no problem. I suggest to check the MWAA task logs in Cloudwatch. You might find why the DAG failed.

**Comment by crupakheti** [comment]
Thank you, @pshen for your contribution to the code base! We are starting the review of this PR.

**Comment by onisim-iacob** [comment]
@pshen in case your 2.6.3 stops working with the same issue as this one https://github.com/aws-samples/amazon-mwaa-examples/issues/61 take a look at my workarround. Thanks for the fix for the import DAG :)
I'm not sure why your MWAA works, but who knows 🤷🏼‍♂️

**Comment by pshen** [comment]
@crupakheti no problem. I'm glad that this PR will be reviewed.

**Comment by pshen** [comment]
@onisim-iacob I guess why triggering the export DAG worked for me. I re-programmed the dags trigger function in Python3. I'm not using the node js code in this repo.

Background: our MWAA environment is completely deployed by Terraform, so I only re-used  export and import DAGs of this repo.

**Comment by crupakheti** [comment]
@pshen Let's get #67 merged first before getting your in as your PR depends on that. Thank you!

**Comment by pshen** [comment]
> @pshen Let's get #67 merged first before getting your in as your PR depends on that. Thank you!

No problem.

**Comment by crupakheti** [comment]
@pshen, @onisim-iacob was kind enough to include and optimize your scripts in his PR (#67 ). So, closing this issue as no further action is needed on this one. Thank you for your contribution!

**Comment by pshen** [comment]
@crupakheti You're welcome!

**Pull request closed without merging**
