### PR TITLE
feat: adding mwaa export import dags for version 2.7.2 2.8.1

### PR DESCRIPTION
**Pull request by pshen**
3 major changes in database schema between 2.6.3 and 2.8.1

Table: task_instance
New column custom_operator_name varchar(1000)

Table: dag_run
New column clear_number [Integer] not null

Table: slot_pool
New column include_deferred[BOOLEAN] NOT NULL

2.6.3
https://airflow.apache.org/docs/apache-airflow/2.6.3/database-erd-ref.html

2.8.1
https://airflow.apache.org/docs/apache-airflow/2.8.1/database-erd-ref.html

*Issue #, if available:*

*Description of changes:*
Since AWS MWAA has released 2.8.1, this PR is adding 2 dags of export and import for this version.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by crupakheti — COMMENTED** [review]
Thank you again, @pshen for your contribution. We will get the PR review started in the tail end of this week.

**Review by crupakheti — CHANGES_REQUESTED** [review]
Hey @pshen, this looks great! Before we merge the change for 2.8.3, can we also get the 2.7.2 included in this PR. On a quick glance, I don't see that we require any changes between these two versions. Are you able to help out?

**Comment by pshen** [comment]
Hi @crupakheti,

I've uploaded the dags for version 2.7.2 as well.

I just found I missed one change in table slot_pool in the previous commit. I've fixed it and also enabled to export this table to csv file.


2 major changes in database schema between 2.6.3 and 2.7.2

Table: task_instance
New column custom_operator_name varchar(1000)

Table: slot_pool
New column include_deferred[BOOLEAN] NOT NULL

2.6.3
https://airflow.apache.org/docs/apache-airflow/2.6.3/database-erd-ref.html

2.7.2
https://airflow.apache.org/docs/apache-airflow/2.7.2/database-erd-ref.html

Ready for your review.

**Review by crupakheti — COMMENTED** [review]
We are working testing both versions. Will get back soon soon. Thank you @pshen!

**Review by crupakheti — CHANGES_REQUESTED** [review]
@pshen Found a small bug in your 2.8.1 export script and have contributed a PR to fix it in your forked repo. Could you please review and approve the PR so we can get this PR merged here. Thank you for you contribution!

https://github.com/pshen/amazon-mwaa-examples/pull/1

**Comment by pshen** [comment]
Hi @crupakheti, thanks for your fix. Just merged your PR to the branch.

**Review by crupakheti — APPROVED** [review]

**Comment by crupakheti** [comment]
@pshen, perfect! Appreciate your contribution to this project! Thank you!

**Pull request merged**
