### PR TITLE
Fix for MWAA Lambda Trigger Error: Ensuring Compatibility with Airflow Versions >=2.6.3

### PR DESCRIPTION
**Pull request by onisim-iacob**
*Issue:*

Export dag returns "botocore.errorfactory.TaskTimedOut: An error occurred (TaskTimedOut) when calling the SendTaskFailure operation: Task Timed Out: 'Provided task does not exist anymore'"

Step function returns an error on run:

image

*Description of changes:*

Code has to be improved to handle versions from 2.5.1 (and downwards) and this is a conditional for upwards starting with 2.6.3.

⚠️ Changing this will stop working for 2.5.1 (and previous versions).⚠️

It happens if you use a MWAA >= 2.6.3. I managed to make it work with `export MWAA_ENV_VERSION=2.6.3` with dags from the [PR#59](https://github.com/aws-samples/amazon-mwaa-examples/pull/59#issue-1957863323).

The problem resides in the "Common" Lambda, which requires a tweak:

❗Broken block for 2.6.3 (around line 13.441 in index.js):
```
  async triggerDag(dagName, configuration) {
    const triggerResult = await this.execute(`dags trigger ${dagName}`, configuration);
    if (!triggerResult.stdOut.includes("triggered: True")) {
      throw new Error(`Dag [${dagName}] trigger failed with the following error: ${JSON.stringify(triggerResult)}`);
    }
    return triggerResult;
  }
```

✅ Fixed:

```
  async triggerDag(dagName, configuration) {
    const triggerResult = await this.execute(`dags trigger -o json ${dagName}`, configuration);
    if (!triggerResult.stdOut.includes('"external_trigger": "True"')) {
      throw new Error(`Dag [${dagName}] trigger failed with the following error: ${JSON.stringify(triggerResult)}`);
    }
    return triggerResult;
  }
```

The Lambda runs the `/aws_mwaa/cli`  call with `dags trigger` which requires an additional `-o json` and the condition for `"external_trigger": "True"`. 

Looking at this document between versions https://airflow.apache.org/docs/apache-airflow/2.6.3/cli-and-env-variables-ref.html#trigger shows that:

```
# 2.5.1
airflow dags trigger [-h] [-c CONF] [-e EXEC_DATE] [-r RUN_ID] [-S SUBDIR]
                     [-v]
                     dag_id
```

```
# 2.6.3
airflow dags trigger [-h] [-c CONF] [-e EXEC_DATE] [--no-replace-microseconds]
                     [-o table, json, yaml, plain] [-r RUN_ID] [-S SUBDIR]
                     [-v]
                     dag_id
```
From 2.6.3 adds extra `[-o table, json, yaml, plain]` parameter which is defaulted to `table`. This breaks the Lambda conditional and throws the _"botocore.errorfactory.TaskTimedOut: An error occurred (TaskTimedOut) when calling the SendTaskFailure operation: Task Timed Out: 'Provided task does not exist anymore'"_ error, which is misleading...

image

By checking the Lambda log, I saw that the call indeed returns a table that breaks the "token" with this format.

image

If you want to see what are all the possible outputs of this `-o` parameter looks like, take a look at this document to invoke the DAG locally: https://docs.aws.amazon.com/mwaa/latest/userguide/call-mwaa-apis-cli.html#create-cli-token-curl

```
CLI_JSON=$(aws mwaa --region YOUR_REGION create-cli-token --name YOUR_ENVIRONMENT_NAME) \
  && CLI_TOKEN=$(echo $CLI_JSON | jq -r '.CliToken') \
  && WEB_SERVER_HOSTNAME=$(echo $CLI_JSON | jq -r '.WebServerHostname') \
  && CLI_RESULTS=$(curl --request POST "https://$WEB_SERVER_HOSTNAME/aws_mwaa/cli" \
  --header "Authorization: Bearer $CLI_TOKEN" \
  --header "Content-Type: text/plain" \
  --data-raw "dags trigger YOUR_DAG_NAME") \
  && echo "Output:" \
  && echo $CLI_RESULTS | jq -r '.stdout' | base64 --decode \
  && echo "Errors:" \
  && echo $CLI_RESULTS | jq -r '.stderr' | base64 --decode
```

With this tests, I managed to debug the lambda call locally, and the problem resides on: `/aws_mwaa/cli` which behaves differently nowadays.

After adding the `-o json` parameter and the `"external_trigger": "True"` conditional, it works just like with the 2.5.1 😎👌🔥

image

Take care!

### CODE REVIEW

**Comment by crupakheti** [comment]
Thank you, @onisim-iacob! We will get this reviewed along with #59.

**Review by crupakheti — CHANGES_REQUESTED** [review]
Great work identifying the root cause here @onisim-iacob! Let's make this PR a little more robust! I have three small changes for you as follows:

1. Please update `lib/infrastructure/mwaa-common-stack.ts` to inject MWAA version as an environment variable as follows:

```typescript
  createDagTriggerFunction(props: MwaaCommonStackProps): lambdajs.NodejsFunction {
    const name = this.getName('dag-trigger-fn');
    const triggerFunc = new lambdajs.NodejsFunction(this, name, {
      entry: join(__dirname, '..', 'lambda', 'dags-trigger-function.ts'),
      depsLockFilePath: join(__dirname, '..', 'lambda', 'package-lock.json'),
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'handler',
      bundling: {
        sourceMap: true,
        target: 'ES2021',
        format: lambdajs.OutputFormat.CJS,
        mainFields: ['module', 'main'],
      },
      ...props.mwaaVpc,
      timeout: cdk.Duration.minutes(10),
      environment: {
        MWAA_ENV_NAME: props.environmentName,
        MWAA_ENV_VERSION: props.environmentVersion,
        NODE_OPTIONS: '--enable-source-maps',
      },
    });

    triggerFunc.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        resources: [`arn:aws:airflow:${props.region}:${props.account}:environment/${props.environmentName}`],
        actions: ['airflow:CreateCliToken'],
      })
    );
    return triggerFunc;
  }
```

2. Update `lib/lambda/dags-trigger-function.ts` to read the version from environment variable and pass it to `DagsCli` object as follows:

```typescript
import { DagsCliResult, DagsCli } from './dags-cli';

const envName = process.env.MWAA_ENV_NAME || '';
const envVersion = process.env.MWAA_ENV_VERSION || '';

export const handler = async (event: Record<string, unknown>): Promise<DagsCliResult> => {
  console.info('Event', event);
  const dagsCli = new DagsCli(envName, envVersion);

  // ... elided for brevity
```

3. Then in `lib/lambda/dag-cli.ts`, could you please use that version to switch between the two commands as follows (need to update both `constructor` and the `triggerDag` method):

```typescript
// ... elided for brevity

export class DagsCli {
  protected token: mwaa.CreateCliTokenCommandOutput;

  constructor(private environmentName: string, private environmentVersion: string, private client = new mwaa.MWAAClient({})) {}

  // ... elided for brevity

  async triggerDag(dagName: string, configuration?: Record<string, string>): Promise<DagsCliResult> {
    const semVer = this.environmentVersion.split('.');

    let command = '';
    if (+semVer[0] <= 2 && +semVer[1] <= 5) {
      command = `dags trigger ${dagName}`;
    } else {
      command = `dags trigger -o json ${dagName}`;
    }

    const triggerResult = await this.execute(command, configuration);
    if (!triggerResult.stdOut.includes('triggered: True')) {
      throw new Error(`Dag [${dagName}] trigger failed with the following error: ${JSON.stringify(triggerResult)}`);
    }
    return triggerResult;
  }

  // ... elided for brevity
'''
After you include these changes, could you please run `npm test`, fix any broken test cases, deploy your stacks, and test out the deployment and then push your commits for review? Happy to help out if you have any questions. Please ask away. Thank you for your contribution!

**Comment by onisim-iacob** [comment]
Hi @crupakheti 

Thanks for the code. I was not able to fix the tests due to the change in the code (I will need some help on that). To deploy the new lambdas on AWS, Node14 is no longer available, so I update it to Node18 in `mwaa-common-stack.ts`, `mwaa-polling-stack.ts`, `mwaa-resuming-stack.ts`  (latest with available project packages is Node18).

Additionally I updated this block with the conditional for the JSON response for ``

```
  async triggerDag(dagName: string, configuration?: Record<string, string>): Promise<DagsCliResult> {
    const semVer = this.environmentVersion.split('.');

    let command = '';
    let resultIncludes = '';
    if (+semVer[0] <= 2 && +semVer[1] <= 5) {
      command = `dags trigger ${dagName}`;
      resultIncludes = 'triggered: True';
    } else {
      command = `dags trigger -o json ${dagName}`;
      resultIncludes = '"external_trigger": "True"';
    }

    const triggerResult = await this.execute(command, configuration);
    if (!triggerResult.stdOut.includes(resultIncludes)) {
      throw new Error(`Dag [${dagName}] trigger failed with the following error: ${JSON.stringify(triggerResult)}`);
    }
    return triggerResult;
  }
```
The packages.json from the Lambda folder, was also pointing to the latest version of the packages. For me the fix was to set the same versions as the main packages.json.

This PR also includes the change for #59. I also added the "2.6.3" DAGs with a fix on "export" for DAG_RUN_SELECT query, which made the DAG rerun the export upon restoring (check comment on DAG).

KR,

**Comment by onisim-iacob** [comment]
Hi @crupakheti

PR with fix for tests approved. All yours!

Thanks!

**Review by crupakheti — APPROVED** [review]
The changes looks good to me. Thank you for your awesome contribution here @onisim-iacob ! We will get this PR merged soon.

**Pull request merged**
