### PR TITLE
Improvements to import_data script following a migration from 2.2.2 to 2.5.1

### PR DESCRIPTION
**Pull request by mjsqu**
Following a successful migration from v2.2.2 to v.2.5.1 I have submitted an updated `import_db.py` script with some improvements that we found useful when running our migration. See the update list below.

…sts - update comments

*Issue #, if available:* N/A

*Description of changes:*

- Addition of sleep statement to prevent throttling errors when reading CloudWatch
- Removal of the `import_db` DAG from the `getDagTasks` query - as `import_db` DAG most probably doesn't exist on the source environment
- More print statements in the CloudWatch migration to track progress
- Check to see if `variable.csv` file exists before reading - some source environments have no variables so this file may not exist

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by umaragu — COMMENTED** [review]
This will impact the existing 2.4.3 migration. ideally, we need a new set of files for 2.2.2 to 2.5.1

**Comment by umaragu** [comment]
The changes will impact the 2.4.3 migration. We need new files for 2.2.2 to 2.5.1 migration

**Comment by mjsqu** [comment]
In my opinion the `import_data.py` code would probably work on 2.4.3 or 2.5.1 - if you test that on both versions then all that's left to do is complete the picture with an `export_data.py` for getting data out of 2.4.3.

**Comment by Mark-Johnston-Te-Whatu-Ora** [comment]
Closing this as the migration approach has changed significantly since I opened this issue, with the introduction of mwaa_dr

**Comment by mjsqu** [comment]
This can be closed, the codebase has moved on a few versions

**Pull request closed without merging**
